resources:
- repo: self

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - docs/*
    - CODEOWNERS
    - .github

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - docs/*
    - CODEOWNERS
    - .github

variables:
  runTests: True
  CONDA_CACHE_DIR: /usr/share/miniconda/envs
  ComponentDetection.Timeout: 900

jobs:
- job: Style
  cancelTimeoutInMinutes: 0
  condition: eq(variables.runTests, 'True')
  pool:
    vmImage: ubuntu-20.04
  steps:
    - task: AzureCLI@2
      displayName: 'Scala Style Check'
      inputs:
        azureSubscription: 'MMLSpark Build'
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: 'sbt scalastyle test:scalastyle'
    - task: UsePythonVersion@00
      inputs:
        versionSpec: '3.8'
    - script: pip install -r requirements.txt
      displayName: 'Install requirements'
    - bash: |
        black --diff --color . && black --check -q .
      displayName: 'Python Style Check'

- job: PublishFeed
  pool:
    vmImage: ubuntu-20.04
  steps:
    - template: templates/kv.yml
    - task: MavenAuthenticate@0
      name: mavenAuthPublicPackages
      displayName: Authenticate with SynapseML_PublicPackages
      inputs:
        artifactsFeeds: SynapseML_PublicPackages
        mavenServiceConnections: SynapseML_PublicPackages-Feed-Connection
    - bash: |
        set -e
        sbt publishSigned
      displayName: Publish to Sonatype Repo
      env:
        STORAGE-KEY: $(storage-key)
        NEXUS-UN: $(nexus-un)
        NEXUS-PW: $(nexus-pw)
        PGP-PRIVATE: $(pgp-private)
        PGP-PUBLIC: $(pgp-public)
        PGP-PW: $(pgp-pw)
        SYNAPSEML_ENABLE_PUBLISH: true
        PUBLISH_TO_FEED: false
    - bash: |
        set -e
        sbt aetherDeploy
      displayName: Publish to Internal Feed
      env:
        DEPLOYMENT_NAME: $(Build.Repository.Name)-$(Build.BuildId)
        ADO-FEED-TOKEN: $(ado-feed-token)
        STORAGE-KEY: $(storage-key)
        NEXUS-UN: $(nexus-un)
        NEXUS-PW: $(nexus-pw)
        PGP-PRIVATE: $(pgp-private)
        PGP-PUBLIC: $(pgp-public)
        PGP-PW: $(pgp-pw)
        SYNAPSEML_ENABLE_PUBLISH: true
        PUBLISH_TO_FEED: true
